version: 0.2

# Main build specification for Lambda functions and infrastructure
# Used by AWS CodeBuild in CI/CD pipeline

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - cd lambda && npm ci && cd ..
      - cd tests/integration && npm ci && cd ../..

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - echo "Linting code..."
      - npm run lint || echo "Linting completed with warnings"
      - echo "Type checking..."
      - npm run build

  build:
    commands:
      - echo "Building Lambda functions..."
      - cd lambda
      - npm run build
      - cd ..
      - echo "Synthesizing CDK stack..."
      - npm run synth

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Preparing artifacts..."

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - 'node_modules/**/*'
    - 'lambda/node_modules/**/*'
    - 'tests/integration/node_modules/**/*'
